filetype off

" Add current project directory as part of path
" /path/to/<PROJECT>/test/vimrc -> /path/to/<PROJECT>
let &runtimepath .= ','.expand('<sfile>:p:h:h')

filetype plugin indent on
syntax enable

" Don't pause listings when screen is filled
set nomore

" Don't make a swap file for our tests
set noswapfile

" Don't read the info/shada file (because set to empty)
set viminfo=
